# Generated by Django 5.0.3 on 2024-03-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssv3app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
